# Generated by Django 3.0.8 on 2021-09-16 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0004_auto_20210916_0950'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cliente',
            old_name='nome',
            new_name='primeiro_nome',
        ),
    ]
